name: 'Test binary'

on:
  push:
    paths:
      - 'practice/basics/basics.py'
      - '.github/workflows/binary.yaml'
  workflow_dispatch:

jobs:
  test-binary:
    timeout-minutes: 1
    name: 'test-binary'
    runs-on: [ self-hosted ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: practice
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install pytest
      - run: |
          pytest practice/basics/basics_test.py::test_binary
